package presenter;

public enum Command {
    C_ADD_JSON,C_ADD_RUNNER,C_CHANGE_SPANISH,C_CHANGE_ENGLISH,C_INFO_RUNNER,C_MEDALS_DELEGATIONS,C_SCHEDULE_PER_COMPETENCE,C_SCHEDULE,C_GENERAL_RESULTS
    ,C_GOLDS,C_SILVERS,C_BRONZE,C_BAR_GRAPHIC, SEARCH_INFO_COMPETITOR, SEARCH_DELEGATION_LIST, SEARCH_BY_MEDAL, C_LIST_COMPETITOR, LIST_GOLDS, LIST_SILVERS, LIST_BRONZES,
    SCORE_BUTTON,GOLDEN_BOY, C_SEARCH_MEDALS_DELEGATION, C_GRAPHICS
}
