package presenter;

public enum Command {
    C_ADD_JSON,C_ADD_RUNNER,C_CHANGE_SPANISH,C_CHANGE_ENGLISH,C_INFO_RUNNER,C_MEDALS_DELEGATIONS,C_SCHEDULE_PER_COMPETENCE,C_SCHEDULE,C_GENERAL_RESULTS
    ,C_GOLDS,C_SILVERS,C_BRONZE,C_BAR_GRAPHIC
}
